---
- name: Manage a VIP
  bigip_virtual_server:
    server: "{{ inventory_hostname }}"
    user: "{{ username }}"
    password: "{{ password }}"
    name: "{{ name }}"
    all_rules:
      - "{{ all_rules }}"
    validate_certs: "false"    
    state: "{{ state }}"
  delegate_to: localhost
...
