---
- include: bigip_virtual_server/manage_vip.yml 
  vars:
    - description: "ansible demo vip" 
    - destination: "10.128.10.88" 
    - name: "ansible_demo_vip" 
    - pool: "ansible_demo_pool" 
    - port: "80" 
    - snat: "Automap"
    - all_profiles: "http"
    - all_rules: ""
  when: state == "present"
...
